### ISSUE TITLE
Republish divide by zero issue?

### ISSUE THREAD

**Issue by mpolichette** [0xPIT/ESParklines#5]
First, a little appreciation:
I have huge appreciation for you right now!

I just started playing around w/ microcontrollers and have been stumbling my way though learning all the things.  I got my little 128x64 OLED going on an ESP32 and was super excited to graph some accelerometer data.

I didn't know how to import code, or know about PlatformIO until i read your README and holy crap my life is soo much better now.

Now the issue:
I got ESparklines running on my ESP32, but I get flatlines at 0.  It looks like you may have solved this with your "fix divide by 0" issue, but I'm not sure another version got published.  I installed latest, and got `0.0.1`.

I'm still new to the ecosystem and PlatformIO so i'm not sure what is involved, but it'd be great to get a new publish out.

Also, I tried making your fix locally and it does work, but it might be drawing outside the defined rect.  I'll debug some more and maybe I'll get a PR in.

**Comment by 0xPIT** [comment]
Thanks for the praise.
Not sure what your issue is, can you post the code?
Else, always use the newest git version of the code.
