### ISSUE TITLE
cant handle negativ values

### ISSUE THREAD

**Issue by axelmagnus** [0xPIT/ESParklines#6]
i tried to plot a sinus curve. well, it  cant interpret negative numbers. maybe have an option of an offset (which is how i solved it)

`  for (int i = 0; i < 50; i++) {
    MySparkLine1.add(20 +amp * sin(i * 0.77)); }`

**Comment by 0xPIT** [comment]
yes, sorry, it's written for unsigned integers, so it makes sense to simply add an offset in your case.
As this sounds like a trivial fix, I won't complicate the code.
Thanks!
